site_name: ICPSR Metadata
site_url: https://icpsr.github.io/metadata/
docs_dir: ../markdown
site_dir: ../site
nav:
  - Home: index.md
  - Schema: schema/icpsr_study_schema.md
  - Style Guide: style/style_guide.md
  - Version History: changes/changes.md
theme:
  name: readthedocs
  prev_next_buttons_location: none
